
package dsmsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FrontEnd", targetNamespace = "http://components.dsms/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FrontEnd {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "invoke", targetNamespace = "http://components.dsms/", className = "dsmsclient.Invoke")
    @ResponseWrapper(localName = "invokeResponse", targetNamespace = "http://components.dsms/", className = "dsmsclient.InvokeResponse")
    @Action(input = "http://components.dsms/FrontEnd/invokeRequest", output = "http://components.dsms/FrontEnd/invokeResponse")
    public String invoke(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
