
package dsmsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FrontEndService", targetNamespace = "http://components.dsms/", wsdlLocation = "http://localhost:9000/dsms/frontend?wsdl")
public class FrontEndService
    extends Service
{

    private final static URL FRONTENDSERVICE_WSDL_LOCATION;
    private final static WebServiceException FRONTENDSERVICE_EXCEPTION;
    private final static QName FRONTENDSERVICE_QNAME = new QName("http://components.dsms/", "FrontEndService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/dsms/frontend?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FRONTENDSERVICE_WSDL_LOCATION = url;
        FRONTENDSERVICE_EXCEPTION = e;
    }

    public FrontEndService() {
        super(__getWsdlLocation(), FRONTENDSERVICE_QNAME);
    }

    public FrontEndService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FRONTENDSERVICE_QNAME, features);
    }

    public FrontEndService(URL wsdlLocation) {
        super(wsdlLocation, FRONTENDSERVICE_QNAME);
    }

    public FrontEndService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FRONTENDSERVICE_QNAME, features);
    }

    public FrontEndService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FrontEndService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FrontEnd
     */
    @WebEndpoint(name = "FrontEndPort")
    public FrontEnd getFrontEndPort() {
        return super.getPort(new QName("http://components.dsms/", "FrontEndPort"), FrontEnd.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FrontEnd
     */
    @WebEndpoint(name = "FrontEndPort")
    public FrontEnd getFrontEndPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://components.dsms/", "FrontEndPort"), FrontEnd.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FRONTENDSERVICE_EXCEPTION!= null) {
            throw FRONTENDSERVICE_EXCEPTION;
        }
        return FRONTENDSERVICE_WSDL_LOCATION;
    }

}
